package com.logtest.masker.patterns;

public enum MaskPatternType {
    BALANCE,
    CONFIDENTIAL_NUMBER,
    EMAIL,
    FULL_ADDRESS,
    INN,
    ISSUER_NAME,
    ISSUER_CODE,
    JWT_TYK_API_KEY_IP_ADDRESS,
    KPP,
    LOCAL_DATE,
    NAME,
    OGRNUL_OR_OGRNIP,
    OFFSET_DATE_TIME,
    OKPO,
    OTHER_DUL_NUMBER,
    OTHER_DUL_SERIES,
    PASSPORT,
    PASSPORT_NUMBER,
    PASSPORT_SERIES,
    PAN,
    PIN,
    PHONE,
    SNILS,
    TEXT_FIELD,
}
